apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "helm.name" . }}
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helm.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "helm.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PORT
            value: "{{ .Values.service.port }}"
          - name: CF_API
            value: "{{ .Values.cf.api }}"
          - name: CF_USERNAME
            value: "{{ .Values.cf.username }}"
          - name: CF_PASSWORD
            value: "{{ .Values.cf.password }}"
          - name: CF_ACCESS_TOKEN
            value: "{{ .Values.cf.accessToken }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # TODO: probe endpoints that don't require basic auth (which will be configurable)
          # livenessProbe:
          #   httpGet:
          #     path: /v2/catalog
          #     port: http
          #     httpHeaders:
          #     # echo -n ":" | base64
          #     - name: Authorization
          #       value: Basic Og==
          # readinessProbe:
          #   httpGet:
          #     path: /v2/catalog
          #     port: http
          #     httpHeaders:
          #     - name: Authorization
          #       value: Basic Og==
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
